/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as RevendedoresRouteImport } from './routes/revendedores'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviosDevolucionesRouteImport } from './routes/envios-devoluciones'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicImageProxyRouteImport } from './routes/api/public/image-proxy'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendedoresRoute = RevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosDevolucionesRoute = EnviosDevolucionesRouteImport.update({
  id: '/envios-devoluciones',
  path: '/envios-devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageProxyRoute = ApiPublicImageProxyRouteImport.update({
  id: '/api/public/image-proxy',
  path: '/api/public/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/envios-devoluciones': typeof EnviosDevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/revendedores': typeof RevendedoresRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/envios-devoluciones': typeof EnviosDevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/revendedores': typeof RevendedoresRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/envios-devoluciones': typeof EnviosDevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/revendedores': typeof RevendedoresRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/envios-devoluciones'
    | '/login'
    | '/marcas'
    | '/revendedores'
    | '/sobre-nosotros'
    | '/api/public/image-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/envios-devoluciones'
    | '/login'
    | '/marcas'
    | '/revendedores'
    | '/sobre-nosotros'
    | '/api/public/image-proxy'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/envios-devoluciones'
    | '/login'
    | '/marcas'
    | '/revendedores'
    | '/sobre-nosotros'
    | '/api/public/image-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  EnviosDevolucionesRoute: typeof EnviosDevolucionesRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  RevendedoresRoute: typeof RevendedoresRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  ApiPublicImageProxyRoute: typeof ApiPublicImageProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendedores': {
      id: '/revendedores'
      path: '/revendedores'
      fullPath: '/revendedores'
      preLoaderRoute: typeof RevendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios-devoluciones': {
      id: '/envios-devoluciones'
      path: '/envios-devoluciones'
      fullPath: '/envios-devoluciones'
      preLoaderRoute: typeof EnviosDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image-proxy': {
      id: '/api/public/image-proxy'
      path: '/api/public/image-proxy'
      fullPath: '/api/public/image-proxy'
      preLoaderRoute: typeof ApiPublicImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  EnviosDevolucionesRoute: EnviosDevolucionesRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  RevendedoresRoute: RevendedoresRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  ApiPublicImageProxyRoute: ApiPublicImageProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
