/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as AdminImagenesMatchRouteImport } from './routes/admin.imagenes-match'
import { Route as ApiPublicImageProxyRouteImport } from './routes/api/public/image-proxy'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/admin/qa',
  path: '/admin/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/admin/precios',
  path: '/admin/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagenesMatchRoute = AdminImagenesMatchRouteImport.update({
  id: '/admin/imagenes-match',
  path: '/admin/imagenes-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageProxyRoute = ApiPublicImageProxyRouteImport.update({
  id: '/api/public/image-proxy',
  path: '/api/public/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/imagenes-match': typeof AdminImagenesMatchRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/qa': typeof AdminQaRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/imagenes-match': typeof AdminImagenesMatchRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/qa': typeof AdminQaRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/imagenes-match': typeof AdminImagenesMatchRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/qa': typeof AdminQaRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/imagenes-match'
    | '/admin/precios'
    | '/admin/qa'
    | '/api/public/image-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/imagenes-match'
    | '/admin/precios'
    | '/admin/qa'
    | '/api/public/image-proxy'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/imagenes-match'
    | '/admin/precios'
    | '/admin/qa'
    | '/api/public/image-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  AdminImagenesMatchRoute: typeof AdminImagenesMatchRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
  AdminQaRoute: typeof AdminQaRoute
  ApiPublicImageProxyRoute: typeof ApiPublicImageProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/admin/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/admin/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imagenes-match': {
      id: '/admin/imagenes-match'
      path: '/admin/imagenes-match'
      fullPath: '/admin/imagenes-match'
      preLoaderRoute: typeof AdminImagenesMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image-proxy': {
      id: '/api/public/image-proxy'
      path: '/api/public/image-proxy'
      fullPath: '/api/public/image-proxy'
      preLoaderRoute: typeof ApiPublicImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  AdminImagenesMatchRoute: AdminImagenesMatchRoute,
  AdminPreciosRoute: AdminPreciosRoute,
  AdminQaRoute: AdminQaRoute,
  ApiPublicImageProxyRoute: ApiPublicImageProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
