/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/admin/precios',
  path: '/admin/precios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/precios': typeof AdminPreciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/precios': typeof AdminPreciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/precios': typeof AdminPreciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/precios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/precios'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/login'
    | '/marcas'
    | '/sobre-nosotros'
    | '/admin/precios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/admin/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  AdminPreciosRoute: AdminPreciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
