-- Reset existing flags - they were biased toward premium items only
UPDATE public.perfumes SET is_recommended = false, is_bestseller = false;

-- RECOMENDADOS DEL EQUIPO (versátiles, distribuidos en precio)
UPDATE public.perfumes SET is_recommended = true WHERE name IN (
  'ARABE LATTAFA KHAMRAH EDP 100ML',
  'ARABE LATTAFA YARA TOUS EDP 100ML',
  'CALVIN KLEIN CK ONE EDT 100ML',
  'JEAN PAUL GAULTIER SCANDAL EDT 100ML',
  'CAROLINA HERRERA 212 VIP BLACK NYC EDP 100M+BL100M (122495',
  'JEAN PAUL GAULTIER LE MALE EDT 75ML',
  'CAROLINA HERRERA GOOD GIRL VERY EDP 50ML',
  'CHRISTIAN DIOR SAUVAGE EDP 100ML'
);

-- MÁS ELEGIDOS (iconos household names)
UPDATE public.perfumes SET is_bestseller = true WHERE name IN (
  'PACO RABANNE 1 MILLION EDT RA 100ML',
  'JEAN PAUL GAULTIER LE MALE LE PARFUM EDP 125ML',
  'CAROLINA HERRERA BAD BOY LE PARFUM EDP 50ML',
  'HUGO BOSS BOTTLED NIGHT EDT 100ML',
  'CAROLINA HERRERA GOOD GIRL BLUSH EDP 80ML',
  'JEAN PAUL GAULTIER SCANDAL LE PARFUM EDP 50ML',
  'BURBERRY GODDESS EDP INTENSE 100ML',
  'ARABE LATTAFA KHAMRAH EDP 100ML'
);